[package]
name = "development-mcp"
version = "0.2.0"
edition = "2021"

[dependencies]
my-http-server = { tag = "0.9.0", git = "https://github.com/MyJetTools/my-http-server.git", features = [
    "static-files",
    "macros",
] }

my-http-utils = { tag = "0.1.0", git = "https://github.com/MyJetTools/my-http-utils.git" }

rust-extensions = { tag = "0.1.5", git = "https://github.com/MyJetTools/rust-extensions.git", features = [
    "with-tokio",
] }

my-ai-agent = { tag = "0.1.0", git = "https://github.com/my-ai-utils/my-ai-agent.git", features = [
    "agent",
] }

my-settings-reader = { tag = "0.5.0", git = "https://github.com/MyJetTools/my-settings-reader.git", features = [
    "background-reader",
] }

mcp-server-middleware = { tag = "0.9.0", git = "https://github.com/my-ai-utils/mcp-server-middleware.git" }

my-logger = { tag = "1.3.0", git = "https://github.com/MyJetTools/my-logger.git" }

my-tls = { tag = "0.1.5", git = "https://github.com/MyJetTools/my-tls.git" }

tokio = { version = "*", features = ["full"] }

serde = { version = "*", features = ["derive"] }
serde_json = "*"

async-trait = "*"

flurl = { tag = "0.7.0", git = "https://github.com/MyJetTools/fl-url.git" }

fastembed = { version = "*" }

arc-swap = "*"

parking_lot = "*"
