mod mcp_resource;
pub use mcp_resource::*;
mod resource_tools;
pub use resource_tools::*;
mod flurl_resource;
pub mod scripts;
pub use flurl_resource::*;
mod http_actions_resource;
pub use http_actions_resource::*;
mod app_bootstrap_resource;
pub use app_bootstrap_resource::*;
mod dioxus_bootstrap_resource;
pub use dioxus_bootstrap_resource::*;
mod cargo_dependencies_resource;
pub use cargo_dependencies_resource::*;
mod my_ssh_resource;
pub use my_ssh_resource::*;
mod my_tcp_sockets_resource;
pub use my_tcp_sockets_resource::*;
mod rust_extensions_resource;
pub use rust_extensions_resource::*;
mod dioxus_design_patterns_resource;
pub use dioxus_design_patterns_resource::*;
mod dioxus_fullstack_patterns_resource;
pub use dioxus_fullstack_patterns_resource::*;
mod my_no_sql_entity_patterns_resource;
pub use my_no_sql_entity_patterns_resource::*;
mod my_grpc_extensions_resource;
pub use my_grpc_extensions_resource::*;
mod dioxus_utils_resource;
pub use dioxus_utils_resource::*;
mod ci_utils_resource;
pub use ci_utils_resource::*;
mod my_postgres_resource;
pub use my_postgres_resource::*;
mod dioxus_admin_ui_kit_resource;
pub use dioxus_admin_ui_kit_resource::*;
mod rust_fix_resource;
pub use rust_fix_resource::*;
mod architect_skill_resource;
pub use architect_skill_resource::*;
mod dioxus_client_side_bootstrap_resource;
pub use dioxus_client_side_bootstrap_resource::*;
mod my_web_socket_client_resource;
pub use my_web_socket_client_resource::*;
mod release_guide_resource;
pub use release_guide_resource::*;
mod application_architecture_resource;
pub use application_architecture_resource::*;
mod performance_considerations_resource;
pub use performance_considerations_resource::*;
mod my_ai_agent_resource;
pub use my_ai_agent_resource::*;
